"""Import every ORM model here so Alembic can discover complete metadata."""

from app.modules.applications.models import (
    Application,
    ApplicationDocument,
    ApplicationEvent,
    ApplicationNotificationPreference,
    ApplicationReminder,
    ApplicationTask,
    ReminderWorkerHealth,
    SavedOpportunity,
)
from app.modules.assistant.models import (
    AssistantAnswer,
    AssistantCitation,
    AssistantConversation,
    AssistantEvaluationRun,
    AssistantEvidencePacket,
    AssistantFeedback,
    AssistantMessage,
    AssistantPrivacyPreference,
)
from app.modules.auth.models import (
    AdminStepUpToken,
    AuditLog,
    EmailVerificationToken,
    PasswordResetToken,
    RefreshToken,
    User,
    WebAuthnChallenge,
    WebAuthnCredential,
)
from app.modules.beta.models import BetaInvitation, BetaLegalAcceptance
from app.modules.catalogue_ingestion.models import (
    CatalogueCandidate,
    CatalogueCandidateSource,
    CatalogueExtractionAttempt,
    CatalogueIngestionRun,
)
from app.modules.community.models import (
    CommunityBlock,
    CommunityBookmark,
    CommunityModerationRecord,
    CommunityPost,
    CommunityPreference,
    CommunityReply,
    CommunityReport,
)
from app.modules.document_lab.models import (
    ApplicationDocumentLink,
    DocumentAnalysis,
    DocumentAnalysisJob,
    DocumentAsset,
    DocumentConsent,
    DocumentExtraction,
    DocumentFeedbackItem,
    DocumentVersion,
)
from app.modules.matching.models import (
    MatchEvaluation,
    MatchEvaluationResult,
    MatchRuleOutcome,
)
from app.modules.operations.models import OperationalJobHealth
from app.modules.opportunities.models import (
    EligibilityRule,
    Opportunity,
    OpportunityCycle,
    Provider,
    Source,
    SourceExcerpt,
    University,
    VerificationRecord,
)
from app.modules.profiles.models import StudentProfile

__all__ = [
    "AdminStepUpToken",
    "Application",
    "ApplicationDocument",
    "ApplicationDocumentLink",
    "ApplicationEvent",
    "ApplicationNotificationPreference",
    "ApplicationReminder",
    "ApplicationTask",
    "AssistantAnswer",
    "AssistantCitation",
    "AssistantConversation",
    "AssistantEvaluationRun",
    "AssistantEvidencePacket",
    "AssistantFeedback",
    "AssistantMessage",
    "AssistantPrivacyPreference",
    "AuditLog",
    "BetaInvitation",
    "BetaLegalAcceptance",
    "CatalogueCandidate",
    "CatalogueCandidateSource",
    "CatalogueExtractionAttempt",
    "CatalogueIngestionRun",
    "CommunityBlock",
    "CommunityBookmark",
    "CommunityModerationRecord",
    "CommunityPost",
    "CommunityPreference",
    "CommunityReply",
    "CommunityReport",
    "DocumentAnalysis",
    "DocumentAnalysisJob",
    "DocumentAsset",
    "DocumentConsent",
    "DocumentExtraction",
    "DocumentFeedbackItem",
    "DocumentVersion",
    "EligibilityRule",
    "EmailVerificationToken",
    "MatchEvaluation",
    "MatchEvaluationResult",
    "MatchRuleOutcome",
    "OperationalJobHealth",
    "Opportunity",
    "OpportunityCycle",
    "PasswordResetToken",
    "Provider",
    "RefreshToken",
    "ReminderWorkerHealth",
    "SavedOpportunity",
    "Source",
    "SourceExcerpt",
    "StudentProfile",
    "University",
    "User",
    "VerificationRecord",
    "WebAuthnChallenge",
    "WebAuthnCredential",
]
