"""Import every ORM model here so Alembic can discover complete metadata."""

from app.modules.applications.models import (
    Application,
    ApplicationDocument,
    ApplicationEvent,
    ApplicationNotificationPreference,
    ApplicationReminder,
    ApplicationTask,
    ReminderWorkerHealth,
    SavedOpportunity,
)
from app.modules.assistant.models import (
    AssistantAnswer,
    AssistantCitation,
    AssistantConversation,
    AssistantEvaluationRun,
    AssistantEvidencePacket,
    AssistantFeedback,
    AssistantMessage,
    AssistantPrivacyPreference,
)
from app.modules.auth.models import (
    AdminStepUpToken,
    AuditLog,
    EmailVerificationToken,
    PasswordResetToken,
    RefreshToken,
    User,
    WebAuthnChallenge,
    WebAuthnCredential,
)
from app.modules.beta.models import BetaInvitation, BetaLegalAcceptance
from app.modules.catalogue_ingestion.discovery_models import (
    CatalogueDiscoveryAssessment,
    CatalogueDiscoveryAttempt,
    CatalogueDiscoveryLead,
    CatalogueDiscoveryObservation,
    CatalogueDiscoveryPromotion,
    CatalogueDiscoveryQuery,
    CatalogueDiscoveryRun,
)
from app.modules.catalogue_ingestion.models import (
    CatalogueCandidate,
    CatalogueCandidateSource,
    CatalogueExtractionAttempt,
    CatalogueIngestionRun,
    CatalogueResumableJob,
    ClassificationDecision,
)
from app.modules.catalogue_ingestion.provider_attempts import CatalogueProviderAttempt
from app.modules.catalogue_ingestion.topology_models import (
    CatalogueCoverageCell,
    CatalogueScopeEdge,
    CatalogueScopeNode,
    CatalogueSourceScopeLink,
)
from app.modules.community.models import (
    CommunityBlock,
    CommunityBookmark,
    CommunityModerationRecord,
    CommunityPost,
    CommunityPreference,
    CommunityReply,
    CommunityReport,
)
from app.modules.document_lab.models import (
    ApplicationDocumentLink,
    DocumentAnalysis,
    DocumentAnalysisJob,
    DocumentAsset,
    DocumentConsent,
    DocumentExtraction,
    DocumentFeedbackItem,
    DocumentVersion,
)
from app.modules.matching.models import (
    MatchEvaluation,
    MatchEvaluationResult,
    MatchRuleOutcome,
)
from app.modules.operations.models import OperationalJobHealth
from app.modules.opportunities.evidence_models import (
    ApplicationStep,
    FieldEvidence,
    FundingComponent,
    RequiredDocument,
    ScopedDeadline,
    SourceSnapshot,
)
from app.modules.opportunities.graph_models import (
    AcademicProgramme,
    ApplicationTrack,
    Institution,
    InstitutionAlias,
    InstitutionParticipation,
    ScholarshipAlias,
    ScholarshipRelationship,
    TrackProgramme,
)
from app.modules.opportunities.models import (
    EligibilityRule,
    Opportunity,
    OpportunityCycle,
    Provider,
    Source,
    SourceExcerpt,
    University,
    VerificationRecord,
)
from app.modules.profiles.models import StudentProfile

__all__ = [
    "AcademicProgramme",
    "AdminStepUpToken",
    "Application",
    "ApplicationDocument",
    "ApplicationDocumentLink",
    "ApplicationEvent",
    "ApplicationNotificationPreference",
    "ApplicationReminder",
    "ApplicationStep",
    "ApplicationTask",
    "ApplicationTrack",
    "AssistantAnswer",
    "AssistantCitation",
    "AssistantConversation",
    "AssistantEvaluationRun",
    "AssistantEvidencePacket",
    "AssistantFeedback",
    "AssistantMessage",
    "AssistantPrivacyPreference",
    "AuditLog",
    "BetaInvitation",
    "BetaLegalAcceptance",
    "CatalogueCandidate",
    "CatalogueCandidateSource",
    "CatalogueCoverageCell",
    "CatalogueDiscoveryAssessment",
    "CatalogueDiscoveryAttempt",
    "CatalogueDiscoveryLead",
    "CatalogueDiscoveryObservation",
    "CatalogueDiscoveryPromotion",
    "CatalogueDiscoveryQuery",
    "CatalogueDiscoveryRun",
    "CatalogueExtractionAttempt",
    "CatalogueIngestionRun",
    "CatalogueProviderAttempt",
    "CatalogueResumableJob",
    "CatalogueScopeEdge",
    "CatalogueScopeNode",
    "CatalogueSourceScopeLink",
    "ClassificationDecision",
    "CommunityBlock",
    "CommunityBookmark",
    "CommunityModerationRecord",
    "CommunityPost",
    "CommunityPreference",
    "CommunityReply",
    "CommunityReport",
    "DocumentAnalysis",
    "DocumentAnalysisJob",
    "DocumentAsset",
    "DocumentConsent",
    "DocumentExtraction",
    "DocumentFeedbackItem",
    "DocumentVersion",
    "EligibilityRule",
    "EmailVerificationToken",
    "FieldEvidence",
    "FundingComponent",
    "Institution",
    "InstitutionAlias",
    "InstitutionParticipation",
    "MatchEvaluation",
    "MatchEvaluationResult",
    "MatchRuleOutcome",
    "OperationalJobHealth",
    "Opportunity",
    "OpportunityCycle",
    "PasswordResetToken",
    "Provider",
    "RefreshToken",
    "ReminderWorkerHealth",
    "RequiredDocument",
    "SavedOpportunity",
    "ScholarshipAlias",
    "ScholarshipRelationship",
    "ScopedDeadline",
    "Source",
    "SourceExcerpt",
    "SourceSnapshot",
    "StudentProfile",
    "TrackProgramme",
    "University",
    "User",
    "VerificationRecord",
    "WebAuthnChallenge",
    "WebAuthnCredential",
]